[package]
name = "lambo"
version = "0.1.0"
edition = "2024"

[dependencies]
petgraph = "0.8.2"
tracing = "0.1.44"
tracing-subscriber = "0.3.22"
tracing-flame = "0.2.0"
tracing-tree = "0.4.1"

[dev-dependencies]
criterion = "0.8.1"

[[bench]]
name = "benchmarks"
harness = false
